---
  - hosts: all
    remote_user: root
    sudo: yes
    tasks:
      - name: Install KRB5 Workstation
        dnf: name=krb5-workstation state=latest
      - name: Install GSSProxy
        dnf: name=gssproxy state=latest
      - name: Install SSSD KRB5 Backend
        dnf: name=sssd-krb5 state=latest
      - name: Install NFS Utils
        dnf: name=nfs-utils state=latest
      - name: Install AutoFS
        dnf: name=autofs state=latest
      - name: Set /etc/krb5.conf
        copy:
            src: configs/etc-krb5.conf
            dest: /etc/krb5.conf
            owner: root
            group: root
            mode: "u=rw,g=r,o=r"
      - name: Add vkdc to /etc/hosts
        lineinfile:
            name: /etc/hosts
            regexp: '^192.168.56.5'
            line: '192.168.56.5 vkdc.nfs.test'
      - name: Add nfs-server to /etc/hosts
        lineinfile:
            name: /etc/hosts
            regexp: '^192.168.56.10'
            line: '192.168.56.10 nfs-server.nfs.test'
      - name: Add nfs-client to /etc/hosts
        lineinfile:
            name: /etc/hosts
            regexp: '^192.168.56.15'
            line: '192.168.56.15 nfs-client.nfs.test'
      - name: Put /tmp/setup-host.sh
        copy:
            src: scripts/setup-host.sh
            dest: /tmp/setup-host.sh
            owner: root
            group: root
            mode: "u=rwx,g=rwx,o=rwx"
      - name: Run /tmp/setup-host.sh
        command: /tmp/setup-host.sh nfs-client
      - name: Create NFS Mount directory
        file: path=/mnt/nfs state=directory
      - name: Create NFS Home directory
        file: path=/mnt/nfs/home state=directory
      - name: Add nfs to /etc/auto.master
        lineinfile:
            name: /etc/auto.master
            regexp: '^/mnt/nfs /etc/auto.home'
            line: '/mnt/nfs /etc/auto.home --timeout=300'
      - name: Set /etc/gssproxy/99-nfs-client.conf
        copy:
            src: configs/etc-gssproxy-99-nfs-client.conf
            dest: /etc/gssproxy/99-nfs-client.conf
            owner: root
            group: root
            mode: "u=rwx,g=rwx,o=rwx"
      - name: Add robbie user
        user:
            name: robbie
            shell: /bin/bash
            createhome: no
            home: /mnt/nfs/home/robbie
      - name: Add alex user
        user:
            name: alex
            shell: /bin/bash
            createhome: no
            home: /mnt/nfs/home/alex
      - name: Enable GSSProxy
        command: systemctl enable gssproxy
      - name: Start GSSProxy
        command: systemctl start gssproxy
      - name: Add SECURE_NFS to /etc/sysconfig/nfs
        lineinfile:
            name: /etc/sysconfig/nfs
            regexp: '^SECURE_NFS="yes"'
            line: 'SECURE_NFS="yes"'
      - name: Restart GSSProxy
        command: systemctl restart gssproxy
