---
  - hosts: all
    remote_user: root
    sudo: yes
    tasks:
      - name: Install KRB5 Server
        dnf: name=krb5-server state=latest
      - name: Install KRB5 Workstation
        dnf: name=krb5-workstation state=latest
      - name: Install GSSProxy
        dnf: name=gssproxy state=latest
      - name: Install SSSD KRB5 Backend
        dnf: name=sssd-krb5 state=latest
      - name: Set /etc/krb5.conf
        copy:
            src: configs/etc-krb5.conf
            dest: /etc/krb5.conf
            owner: root
            group: root
            mode: "u=rw,g=r,o=r"
      - name: Set /etc/kdc.conf
        copy:
            src: configs/etc-kdc.conf
            dest: /etc/kdc.conf
            owner: root
            group: root
            mode: "u=rw,g=r,o=r"
      - name: Set /etc/kdc.conf
        copy:
            src: configs/var-kerberos-krb5kdc-kadm5.acl
            dest: /var/kerberos/krb5kdc/kadm5.acl
            owner: root
            group: root
            mode: 0600
      - name: Put /tmp/setup-kdc.sh
        copy:
            src: scripts/setup-kdc.sh
            dest: /tmp/setup-kdc.sh
            owner: root
            group: root
            mode: "u=rwx,g=rwx,o=rwx"
      - name: Run /tmp/setup-kdc.sh
        command: /tmp/setup-kdc.sh
      - name: Add vkdc to /etc/hosts
        lineinfile:
            path: /etc/hosts
            regexp: '^192.168.56.5'
            line: '192.168.56.5 vkdc.mivehind.net'
      - name: Add nfs-server to /etc/hosts
        lineinfile:
            path: /etc/hosts
            regexp: '^192.168.56.10'
            line: '192.168.56.10 nfs-server.mivehind.net'
      - name: Add nfs-client to /etc/hosts
        lineinfile:
            path: /etc/hosts
            regexp: '^192.168.56.15'
            line: '192.168.56.15 nfs-client.mivehind.net'
      - name: Put /tmp/setup-host.sh
        copy:
            src: scripts/setup-host.sh
            dest: /tmp/setup-host.sh
            owner: root
            group: root
            mode: "u=rwx,g=rwx,o=rwx"
      - name: Run /tmp/setup-host.sh
        command: /tmp/setup-host.sh vkdc
      - name: Add robbie user
        command: useradd -m -s /bin/bash robbie
        args:
            creates: /home/robbie
      - name: Add alex user
        command: useradd -m -s /bin/bash alex
        args:
            creates: /home/alex
